@startuml

skinparam ClassAttributeIconSize 0

class AuthController <<Controller>> {
    + join()
    + checkUsernamePassword()
    + logout()
    - validateUsername()
    - validatePassword()
}
class UserModel <<Entity>> {
    + persist()
    + nameExists()
    + findByName()
}

AuthController "1" -- "1" UserModel 

@enduml