@startuml
class ProfileController {
    + getCurrentProfile()
    + getCitizenProfile()
    + StoreProfile(Profile)
}
entity Profile {
    + setProfile(Profile)
    + getProfile()
}
class ProfileBoundary {
    + getCurrentProfile()
    + displayUpdateProfilePageWithCurrentProfile()
    + getCitizenProfile()
    + displayCitizenProfile()
}

ProfileController "1" -- "1" ProfileBoundary
ProfileController "1" -- "0..*" Profile
@enduml