@startuml

class AdministerProfileBoundary <<Boundary>> {
    + administerProfile(string username)
    + displayAccountStatus()
    + displayPrivilegeLevel()
    + displayUsername()
    + displayWayToModifyAccountStatus()
    + displayWayToModifyPrivilegeLevel()
    + displayWayToModifyUsername()
    + displayWayToModifyPassword()
    + proposeChangeToAccountStatus(string newStatus)
    + proposeChangeToPrivilegeLevel(string newLevel)
    + proposeChangeToUsername(string newUsername)
    + proposeChangeToPassword(string newPassword)
    + displayChangesValid()
    + requestChangeConfirmation()
    + submitChanges()
}

class AdministerProfileController <<Controller>> {
    + findUserProfile(string username)
    + validateProposedAccountStatus(string newStatus)
    + validateProposedPrivilegeLevel(string newLevel)
    + validateProposedUsername(string newUsername)
    + validateProposedPassword(string newPassword)
    + saveProfileChanges()
    + systemAction()
}

entity User {
    + checkUsername(string username)
    + getProfile()
}

entity UserProfile {
    + updateAccountStatus(string newAccountStatus)
    + updatePrivilegeLevel(string newLevel)
    + updateUsername(string newUsername)
    + updatePassword(string newPassword)
}

class LoggedInUserBoundary <<Boundary>> {
    + logoutWithMessage()
}

AdministerProfileBoundary "1" -- "1" AdministerProfileController
AdministerProfileController "1" -- "1..*" User
User "1" -- "1" UserProfile
AdministerProfileController "1" -- "0..*" LoggedInUserBoundary

@enduml