@startuml
class Client
class Target <<interface>>
class PerformanceTestModel
class PostgresSQLClient
Target : saveResult()
PerformanceTestModel : saveResult()
PostgresSQLClient : saveResultPostgresSQL()

note right of Target
Not present in our implementation
end note

note bottom of PerformanceTestModel
Adapter
end note

note bottom of PostgresSQLClient
Adaptee
end note

Client -> Target
Target <|.. PerformanceTestModel 
PerformanceTestModel -> PostgresSQLClient
@enduml
