@startuml

class LostAndFoundBoundary{
    openLostAndFoundPost()
    resolveLostAndFoundPost()
    displayLostAndFoundPost()
    updatePostList()
}

class LostAndFoundController{
    getLostAndFoundPost(sender)
    resolvePost(postid)
}

entity Post{
    resolvePost(postid)
}

LostAndFoundBoundary "1" -- "1" LostAndFoundController
LostAndFoundController "1" -- "0..*" Post

@enduml
